#!/bin/bash
set -e

HTTP_CONFD_DIR="/etc/httpd/conf.d"
HTTP_CONF_DIR="/etc/httpd/conf"

DB_HOST=${DB_HOST:-}
DB_NAME=${DB_NAME:-}
DB_USER=${DB_USER:-}
DB_PASS=${DB_PASS:-}
DB_TYPE=${DB_TYPE:-mysql}
SVN_RELATIVE_URL_ROOT=${SVN_RELATIVE_URL_ROOT:-/svn}
GIT_RELATIVE_URL_ROOT=${GIT_RELATIVE_URL_ROOT:-/git}
HTTPD_USER=${HTTPD_USER:-redmine}
HTTPD_GROUP=${HTTPD_GROUP:-redmine}

# is a mysql or postgresql database linked?
# requires that the mysql or postgresql containers have exposed
# port 3306 and 5432 respectively.
if [ -n "${MYSQL_PORT_3306_TCP_ADDR}" ]; then
	DB_TYPE=mysql
	DB_HOST=${DB_HOST:-${MYSQL_PORT_3306_TCP_ADDR}}
	DB_PORT=${DB_PORT:-${MYSQL_PORT_3306_TCP_PORT}}
	
	# support for linked sameersbn/mysql image
	DB_USER=${DB_USER:-${MYSQL_ENV_DB_USER}}
	DB_PASS=${DB_PASS:-${MYSQL_ENV_DB_PASS}}
	DB_NAME=${DB_NAME:-${MYSQL_ENV_DB_NAME}}
	
	# support for linked orchardup/mysql and centurylink/mysql image
	# also supports official mysql image
	DB_USER=${DB_USER:-${MYSQL_ENV_MYSQL_USER}}
	DB_PASS=${DB_PASS:-${MYSQL_ENV_MYSQL_PASSWORD}}
	DB_NAME=${DB_NAME:-${MYSQL_ENV_MYSQL_DATABASE}}
elif [ -n "${POSTGRESQL_PORT_5432_TCP_ADDR}" ]; then
	DB_TYPE=postgres
	DB_HOST=${DB_HOST:-${POSTGRESQL_PORT_5432_TCP_ADDR}}
	DB_PORT=${DB_PORT:-${POSTGRESQL_PORT_5432_TCP_PORT}}
	
	# support for linked official postgres image
	DB_USER=${DB_USER:-${POSTGRESQL_ENV_POSTGRES_USER}}
	DB_PASS=${DB_PASS:-${POSTGRESQL_ENV_POSTGRES_PASSWORD}}
	DB_NAME=${DB_NAME:-${DB_USER}}
	
	# support for linked sameersbn/postgresql image
	DB_USER=${DB_USER:-${POSTGRESQL_ENV_DB_USER}}
	DB_PASS=${DB_PASS:-${POSTGRESQL_ENV_DB_PASS}}
	DB_NAME=${DB_NAME:-${POSTGRESQL_ENV_DB_NAME}}
	
	# support for linked orchardup/postgresql image
	DB_USER=${DB_USER:-${POSTGRESQL_ENV_POSTGRESQL_USER}}
	DB_PASS=${DB_PASS:-${POSTGRESQL_ENV_POSTGRESQL_PASS}}
	DB_NAME=${DB_NAME:-${POSTGRESQL_ENV_POSTGRESQL_DB}}
	
	# support for linked paintedfox/postgresql image
	DB_USER=${DB_USER:-${POSTGRESQL_ENV_USER}}
	DB_PASS=${DB_PASS:-${POSTGRESQL_ENV_PASS}}
	DB_NAME=${DB_NAME:-${POSTGRESQL_ENV_DB}}
fi

if [ -z "${DB_HOST}" ]; then
	echo "ERROR: "
	echo "  Please configure the database connection."
	echo "  Refer http://git.io/JkE-cw for more information."
	echo "  Cannot continue without a database. Aborting..."
	exit 1
fi

# use default port number if it is still not set
case "${DB_TYPE}" in
	mysql) DB_PORT=${DB_PORT:-3306} ;;
	postgres) DB_PORT=${DB_PORT:-5432} ;;
	*)
		echo "ERROR: "
		echo "  Please specify the database type in use via the DB_TYPE configuration option."
		echo "  Accepted values are \"postgres\" or \"mysql\". Aborting..."
		exit 1
		;;
esac

sed 's/{{DB_HOST}}/'"${DB_HOST}"'/' -i ${HTTP_CONFD_DIR}/redmine_scm.conf
sed 's/{{DB_PORT}}/'"${DB_PORT}"'/' -i ${HTTP_CONFD_DIR}/redmine_scm.conf
sed 's/{{DB_NAME}}/'"${DB_NAME}"'/' -i ${HTTP_CONFD_DIR}/redmine_scm.conf
sed 's/{{DB_USER}}/'"${DB_USER}"'/' -i ${HTTP_CONFD_DIR}/redmine_scm.conf
sed 's/{{DB_PASS}}/'"${DB_PASS}"'/' -i ${HTTP_CONFD_DIR}/redmine_scm.conf
sed 's,{{SVN_RELATIVE_URL_ROOT}},'"${SVN_RELATIVE_URL_ROOT}"',' -i ${HTTP_CONFD_DIR}/redmine_scm.conf
sed 's,{{GIT_RELATIVE_URL_ROOT}},'"${GIT_RELATIVE_URL_ROOT}"',' -i ${HTTP_CONFD_DIR}/redmine_scm.conf

sed 's,User apache,'"User ${HTTPD_USER}"',' -i ${HTTP_CONF_DIR}/httpd.conf
sed 's,Group apache,'"Group ${HTTPD_GROUP}"',' -i ${HTTP_CONF_DIR}/httpd.conf

exec /usr/bin/supervisord -n -c /etc/supervisord.conf

exit 0
